import type { Metadata } from "next";
import { getFeedEntries, type FeedEntry } from "@/lib/feed";
import { Container } from "@/components/layout/container";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { FadeInStagger } from "@/components/animation/fade-in-stagger";

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Discovery Feed | DRIP Agent",
  description:
    "Autonomous intelligence briefs generated by the DRIP research agent. Company profiles, market signals, and strategic analysis — updated daily.",
};

// ─── Helpers ────────────────────────────────────────────────────────

function formatRelativeTime(isoDate: string): string {
  const now = Date.now();
  const then = new Date(isoDate).getTime();
  const diffMs = now - then;

  const minutes = Math.floor(diffMs / 60_000);
  if (minutes < 1) return "just now";
  if (minutes < 60) return `${minutes}m ago`;

  const hours = Math.floor(minutes / 60);
  if (hours < 24) return `${hours}h ago`;

  const days = Math.floor(hours / 24);
  if (days < 30) return `${days}d ago`;

  return new Date(isoDate).toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
}

function truncateSummary(summary: string, maxLength = 180): string {
  // Strip markdown formatting for card preview
  const plain = summary
    .replace(/#{1,6}\s/g, "")
    .replace(/\*\*([^*]+)\*\*/g, "$1")
    .replace(/\*([^*]+)\*/g, "$1")
    .replace(/`([^`]+)`/g, "$1")
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
    .replace(/\n+/g, " ")
    .trim();

  if (plain.length <= maxLength) return plain;
  return plain.slice(0, maxLength).replace(/\s+\S*$/, "") + "…";
}

function badgeVariantForType(type: FeedEntry["type"]): "accent" | "info" {
  return type === "company" ? "accent" : "info";
}

function labelForType(type: FeedEntry["type"]): string {
  switch (type) {
    case "company":
      return "Company";
    case "person":
      return "Person";
    default:
      return "Research";
  }
}

// ─── Components ─────────────────────────────────────────────────────

function EmptyState() {
  return (
    <Card variant="elevated" className="mx-auto max-w-lg text-center py-16">
      <div className="mb-4 text-4xl">◉</div>
      <h2 className="mb-3 text-lg font-semibold text-icy-aqua">
        Sensors Calibrating
      </h2>
      <p className="text-sm leading-relaxed text-ocean-mist/70">
        DRIP is calibrating its sensors. Discovery feed entries will appear here
        once the autonomous agent begins research.
      </p>
    </Card>
  );
}

function FeedCard({
  entry,
  featured = false,
}: {
  entry: FeedEntry;
  featured?: boolean;
}) {
  return (
    <Card variant={featured ? "featured" : "default"} className="flex flex-col gap-3">
      <div className="flex items-center justify-between gap-2">
        <Badge variant={badgeVariantForType(entry.type)}>
          {labelForType(entry.type)}
        </Badge>
        <span className="text-xs text-ocean-mist/50">
          {formatRelativeTime(entry.createdAt)}
        </span>
      </div>

      <h3
        className={
          featured
            ? "text-lg font-semibold text-ghost-white"
            : "text-base font-medium text-ghost-white"
        }
      >
        {entry.title}
      </h3>

      <p className="text-xs font-mono text-ocean-mist/40 uppercase tracking-wider">
        {entry.topic}
      </p>

      <p className="text-sm leading-relaxed text-ocean-mist/70">
        {truncateSummary(entry.summary, featured ? 280 : 180)}
      </p>
    </Card>
  );
}

// ─── Page ───────────────────────────────────────────────────────────

export default async function FeedPage() {
  const entries = await getFeedEntries(20);

  return (
    <Container className="py-12">
      <div className="mb-8">
        <h1 className="text-2xl font-bold tracking-tight text-ghost-white sm:text-3xl">
          Discovery Feed
        </h1>
        <p className="mt-2 text-sm text-ocean-mist/60">
          Autonomous intelligence briefs from the DRIP research agent
        </p>
      </div>

      {entries.length === 0 ? (
        <EmptyState />
      ) : (
        <FadeInStagger className="grid grid-cols-1 gap-5 md:grid-cols-2 lg:grid-cols-3">
          {entries.map((entry, i) => (
            <FeedCard key={entry.id} entry={entry} featured={i === 0} />
          ))}
        </FadeInStagger>
      )}
    </Container>
  );
}
