import { NextResponse } from "next/server";
import { loadPosts } from "@/lib/agent-brain";

/**
 * GET /api/agent/feed — Get agent's autonomous posts
 *
 * Returns the latest posts generated by the autonomous agent brain.
 * These are insights, research notes, and market observations.
 */
export async function GET(req: Request) {
  const url = new URL(req.url);
  const limit = Math.min(parseInt(url.searchParams.get("limit") || "20"), 50);

  const posts = loadPosts().slice(0, limit);

  return NextResponse.json({
    posts,
    total: posts.length,
    updatedAt: new Date().toISOString(),
  });
}
